### ISSUE TITLE
UIWebView Deprecation Dec 2020

### ISSUE THREAD

**Issue by annawaiwong** [bambora/APAC-BNPayment-iOS#14]
Hi 

Our company currently uses your sdk for our iOS apps, and Apple we will require the latest sdk to remove the use of UIWebViews . Apple will start rejecting app submissions for existing apps in Dec 2020 if it detects UIWebView references in code.

I'll be reaching out to account managers from our company, but I'm also hoping that you guys actively maintain/view issues logged here as well and actively provide the required sdk support for clients.

Apple article reference: https://developer.apple.com/news/?id=12232019b

**Comment by vishnusasikumar-bidone** [comment]
Hi 

We are in a similar situation and we do have new apps going into the store and are potentially facing rejection, which could affect our other apps as well. I hope you guys update the SDK soon and make the necessary changes.

**Comment by annawaiwong** [comment]
I've been told through our account reps that there is one in the works and coming around the 15th Sept. So hopefully we'll be able to start testing the update soon.

**Comment by annawaiwong** [comment]
Looks like this is resolved for us with the new release
